BEGIN TRANSACTION;
DROP TABLE IF EXISTS "car";
CREATE TABLE IF NOT EXISTS "car" (
	"car_id"	,
	"brand" ,
	"model"	,
	"year"	INTEGER,
	"price" INTEGER,
	"km_driven" INTEGER,
	"fuel_type" ,
	"seller_type" ,
	"transmission" ,
	"owners_info" ,
	"fuel_consumption" REAL,
	"engine" REAL,
	"max_power" INTEGER,
	"torque" INTEGER,
	"seats" INTEGER,
	"image_url" ,
	"user_id"
);
DROP TABLE IF EXISTS "order_info";
CREATE TABLE IF NOT EXISTS "order_info" (
	"order_info_id"	,
	"datetime"	,
	"total"	,
	"user_id"
);
DROP TABLE IF EXISTS "user";
CREATE TABLE IF NOT EXISTS "user" (
	"user_id" INTEGER PRIMARY KEY,
	"first_name"	,
	"last_name"	,
	"email"	UNIQUE,
	"hash_key" ,
	"hashed_password"	,
	"salt" ,
	"is_admin" BOOLEAN DEFAULT 0
);
DROP TABLE IF EXISTS "car_in_order";
CREATE TABLE IF NOT EXISTS "car_in_order" (
	"order_info_id"	,
	"car_id"
);
DROP TABLE IF EXISTS "basket";
CREATE TABLE IF NOT EXISTS "basket" (
	"user_id"	,
	"car_id"
);
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("1","Ford","Focus","2017","42995","22378","Petrol","Individual","Manual","First Owner","59.06","2.3","345","325","5","https://m.atcdn.co.uk/a/media/w800h600/5851b353a37d4541aa3d1c7c50a16848.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("2","Mazda","MX-5","2017","16999","6877","Petrol","Dealer","Manual","Second Owner","72.10","1.5","130","112","4","https://m.atcdn.co.uk/a/media/w1024/585eef6dbaf44c719ab4c5524fb45fb7.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("3","MINI","Cooper Roadster Convertible","2012","9000","44540","Petrol","Dealer","Manual","Second Owner","42.80","1.6","190","192","2","https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/11q4/424154/2012-mini-cooper-cooper-s-john-cooper-works-roadster-official-photos-and-info-car-and-driver-photo-426761-s-original.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("4","MINI","Cooper Roadster Convertible","2012","8483","68897","Petrol","Individual","Manual","Second Owner","42.80","1.6","190","192","2","https://i.pinimg.com/originals/1a/da/f3/1adaf324acd7729df87fc4cdb7565763.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("5","AM","General Hummer","2000","68999","87972","Diesel","Dealer","Manual","Second Owner","19.50","3.7","244","241","5","https://i.ytimg.com/vi/AYStSXy1jcI/hqdefault.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("6","AM","General Hummer","2000","53029","103873","Diesel","Individual","Manual","Second Owner","19.50","3.7","244","241","5","https://cdn1.mecum.com/auctions/az0321/az0321-453784/images/1-1615311386441@2x.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("7","BMW","Z4 Convertible","2012","12978","74407","Petrol","Dealer","Automatic","Second Owner","41.50","2.0","245","258","2","https://media.evo.co.uk/image/private/s--m-ISaAI7--/f_auto,t_content-image-full-mobile@1/v1556262873/evo/images/dir_947/car_photo_473836.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("8","BMW","Z4 Convertible","2012","14999","83287","Petrol","Individual","Automatic","Second Owner","41.50","2.0","245","258","2","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/2011_BMW_Z4_sDrive23i_M_Sport_Highline_2.5.jpg/800px-2011_BMW_Z4_sDrive23i_M_Sport_Highline_2.5.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("9","Bugatti","Veyron Convertible","2009","1902999","124","Petrol","Dealer","Manual","Second Owner","8.00","8.0","1001","922","2","https://pictures.topspeed.com/IMG/crop/200906/2009-bugatti-veyron-16-4--43_800x0w.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("10","Bugatti","Veyron Convertible","2009","1093042","8009","Petrol","Individual","Manual","Second Owner","8.00","8.0","1001","922","2","https://images.hgmsites.net/hug/2009-bugatti-veyron-16-4-grand-sport_100182264_h.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("11","Bugatti","Veyron Coupe","2009","983847","32092","Petrol","Dealer","Manual","Second Owner","8.00","8.0","1001","922","2","https://slaylebrity.com/wp-content/uploads/2017/07/image-745.jpeg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("12","Bugatti","Veyron Coupe","2009","864957","50198","Petrol","Individual","Manual","Second Owner","8.00","8.0","1001","922","2","https://o.aolcdn.com/images/dims3/GLOB/legacy_thumbnail/800x450/format/jpg/quality/85/http://www.blogcdn.com/www.autoblog.com/media/2009/07/bugattigrandsportfd_47_opt.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("13","Geo","Metro Convertible","1993","500","126877","Petrol","Dealer","Manual","Second Owner","2.00","1.1","59","66","5","https://bringatrailer.com/wp-content/uploads/2018/03/5aa6a8f88dc1b_IMG_7991_1024.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("14","Geo","Metro Convertible","1993","999","98020","Petrol","Individual","Manual","Second Owner","2.00","1.1","59","66","5","https://cloud.leparking.fr/2021/12/05/08/08/geo-metro-lsi-blue_8361141321.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("15","Jaguar","XK XKR","2012","35997","16877","Petrol","Dealer","Manual","Second Owner","18.00","5.0","385","380","2","https://cimg2.ibsrv.net/ibimg/hgm/1024x576-1/100/383/2012-jaguar-xk-xkr-s_100383418.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("16","Jaguar","XK XKR","2012","38329","26457","Petrol","Dealer","Manual","Second Owner","18.00","5.0","385","380","2","https://s.aolcdn.com/commerce/autodata/images/USC20JAC111A021001.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("17","Jeep","Liberty","2012","16000","46877","Diesel","Dealer","Manual","Second Owner","14.00","3.7","210","199","5","https://upload.wikimedia.org/wikipedia/commons/4/48/2012_Jeep_Liberty_--_NHTSA.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("18","Jeep","Liberty","2012","19999","26567","Diesel","Individual","Manual","Second Owner","14.00","3.7","210","199","5","https://www.conceptcarz.com/images/Jeep/2012-Jeep_Liberty-SUV_Image-01.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("19","Mercedes-Benz","300-Class","1993","6999","97801","Petrol","Dealer","Automatic","Second Owner","23.00","3.2","217","201","7","https://fueltankcap.com/image/1994_mercedes-benz_500-class_fq_oem_2_400.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("20","Mercedes-Benz","300-Class","1993","1034","146877","Petrol","Dealer","Automatic","Second Owner","23.00","3.2","217","201","7","https://static.cargurus.com/images/site/2010/07/18/07/29/1993_mercedes-benz_300-class_2_dr_300ce_coupe-pic-4005332418707363175-640x480.jpeg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("21","Mercedes-Benz","Sprinter","2012","36999","34007","Diesel","Individual","Manual","Second Owner","35.30","2.1","141","243","7","https://www.autotrader.com/wp-content/uploads/2020/02/169758.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("22","Mercedes-Benz","Sprinter","2012","42482","26877","Diesel","Dealer","Manual","Second Owner","35.30","2.1","141","243","7","https://www.motortrend.com/uploads/sites/5/2014/02/2012-Mercedes-Benz-Sprinter-front-view2.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("23","Mitsubishi","Lancer Sedan","2012","76182","3137","Petrol","Dealer","Manual","Second Owner","8.10","2.0","148","140","5","https://upload.wikimedia.org/wikipedia/commons/8/82/2012_Mitsubishi_Lancer_SE_sedan_--_02-04-2012_1.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("24","Mitsubishi","Lancer Sedan","2012","96929","1877","Petrol","Individual","Manual","Second Owner","8.10","2.0","148","140","5","https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/dp/images/uploads/Lancer-VRX-w.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("25","Tesla","Model S Sedan","2012","99999","1001","Electric","Dealer","Automatic","Second Owner","265.0","1.0","356","400","5","https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/11q3/409394/2012-tesla-model-s-first-ride-reviews-car-and-driver-photo-424078-s-original.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("26","Tesla","Model S Sedan","2012","116999","234","Electric","Dealer","Automatic","Second Owner","265.0","1.0","356","400","5","https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/dp/albums/album-3604/lg/TeslaModelS-gallery2.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("27","Scion","xD Hatchback","2012","929","201001","Petrol","Individual","Manual","Second Owner","27.30","1.8","128","125","5","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/2008_Scion_xD_in_Silver%2C_front_right.jpg/640px-2008_Scion_xD_in_Silver%2C_front_right.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("28","Scion","xD Hatchback","2012","219","999999","Petrol","Dealer","Manual","Second Owner","27.30","1.8","128","125","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhYA5VgnqtyYI-fJMrun64EBmNHAIGBh1bnA&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("29","Aston Martin","Virage Coupe","2012","116999","877","Petrol","Dealer","Manual","Second Owner","15.60","8.0","489","501","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEGdIg0Iu64E6gFK3y72PpO7YNzXoJefAYbQ&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("30","Aston Martin","Virage Coupe","2012","161000","6","Petrol","Dealer","Manual","Second Owner","15.60","8.0","489","501","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_116Mpk_EmPftKcoZ3nY1Ib6so5iYi-1uGA&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("31","Rolls-Royce","Phantom Sedan","2012","162999","7","Petrol","Individual","Automatic","Second Owner","12.01","6.8","453","531","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTds082Xw_fbN9RsRhehStZZYF2-3z_iuWNMQ&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("32","Rolls-Royce","Phantom Sedan","2012","216999","1","Petrol","Dealer","Automatic","Second Owner","12.01","6.8","453","531","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkSWbr8sC-iBQ17QWuw0Z6HwXr-j8YTzoYyw&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("33","Spyker","C8 Coupe","2009","87,000","23877","Petrol","Dealer","Manual","Second Owner","23.20","4.0","620","637","2","https://barrettjacksoncdn.azureedge.net/staging/carlist/items/Fullsize/Cars/116106/116106_Side_Profile_Web.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("34","Spyker","C8 Coupe","2009","92,999","21877","Petrol","Individual","Manual","Second Owner","23.20","4.0","620","637","2","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAqq7nyviLlot7iCsK6yzKoTSaGJQ_OBwV7g&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("35","Suzuki","SX4 Hatchback","2012","6999","83877","Petrol","Dealer","Manual","Second Owner","45.60","1.6","118","115","5","https://i.ytimg.com/vi/g8cRGeiP-WU/maxresdefault.jpg","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("36","Suzuki","SX4 Hatchback","2012","8000","63877","Petrol","Dealer","Manual","Second Owner","45.60","1.6","118","115","5","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaZOoBCLfxr4OyMa8ArlOBvxq4JWb2AFXE3w&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("37","Bentley","Continental GT Coupe","2012","64983","72877","Petrol","Dealer","Manual","Second Owner","7.35","6.0","507","545","2","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzoVceD6QySq_tmU-pGwoqmnqS5wTDLJjULQ&usqp=CAU","1");
INSERT INTO "car" ("car_id","brand","model","year","price","km_driven","fuel_type","seller_type","transmission","owners_info","fuel_consumption","engine","max_power","torque","seats","image_url","user_id") VALUES ("38","Bentley","Continental GT Coupe","2012","103487","2817","Petrol","Dealer","Manual","Second Owner","7.35","6.0","507","545","2","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB32dRFqbS9TP0b_orG3vGTe2yU8fFjVEDQQ&usqp=CAU","1");
INSERT INTO "order_info" ("order_info_id","datetime","total","user_id") VALUES ('1','2022-01-26 13:45:12','8000','1');
INSERT INTO "user" ("user_id","first_name","last_name","email","hashed_password","salt") VALUES ('1','John','Smith','johnsmith@gmail.com','abc123','321');
INSERT INTO "user" ("user_id","first_name","last_name","email","hashed_password","salt") VALUES ('2','Bob','Marley','bobmarley@gmail.com','abc123','321');
INSERT INTO "car_in_order" ("order_info_id","car_id") VALUES ('1','2');
INSERT INTO "basket" ("user_id","car_id") VALUES ('2','1');
COMMIT;
